# Generated by Django 4.0.6 on 2022-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
