# Generated by Django 4.0.6 on 2022-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='.\x07uctions\\static\x07uctions\\images'),
        ),
    ]
