# Generated by Django 4.0.6 on 2022-07-08 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listedby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
