# Generated by Django 4.0.6 on 2022-07-11 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_product_listed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='watchlist', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(blank=True, related_name='watchlisted', to='auctions.product')),
            ],
        ),
    ]
